language: java

sudo: required

# required for oraclejdk9
dist: trusty

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

matrix:
  allow_failures:
    - jdk: oraclejdk9

script:
   ./mvnw clean install;

notifications:
  slack:
    on_success: never  # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never    # options: [always|never|change] default: always
